# Generated by Django 6.0.6 on 2026-06-16 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default CA', max_length=100)),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('private_key_pem', models.TextField(help_text='PEM-encoded private key')),
                ('certificate_pem', models.TextField(help_text='PEM-encoded certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('cert_type', models.CharField(choices=[('client', 'Client Certificate'), ('server', 'Server Certificate')], max_length=10)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('certificate_pem', models.TextField()),
                ('private_key_pem', models.TextField(blank=True, help_text='Empty if CSR was uploaded', null=True)),
                ('csr_pem', models.TextField(blank=True, help_text='Empty if private key was generated on server', null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
