# Generated by Django 6.0.6 on 2026-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('private_key_pem', models.TextField(help_text='PEM-encoded account private key')),
                ('regr_json', models.TextField(help_text='JSON representation of registration resource')),
                ('is_staging', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcmeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('validation', models.TextField(help_text='ACME key authorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='issuer_type',
            field=models.CharField(choices=[('local', 'Local CA'), ('letsencrypt', "Let's Encrypt")], default='local', max_length=20),
        ),
    ]
