# Generated by Django 6.0.6 on 2026-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_acmeaccount_acmechallenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='kms_key_id',
            field=models.CharField(blank=True, help_text='vHSM KMS Key UUID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='encrypted_key_b64',
            field=models.TextField(blank=True, help_text='AES-GCM encrypted private key', null=True),
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='kms_nonce_b64',
            field=models.CharField(blank=True, help_text='KMS transit encryption nonce', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text='PEM-encoded private key (empty if using KMS)', null=True),
        ),
        migrations.AlterField(
            model_name='issuedcertificate',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text='Empty if CSR was uploaded or using KMS envelope encryption', null=True),
        ),
    ]
